export const FETCH_WORKITEMS_DETAIL = 'FETCH_WORKITEMS_DETAIL';

export const FETCH_WORKITEMS_PENDING = 'FETCH_WORKITEMS_PENDING';
export const FETCH_WORKITEMS_SUCCESS = 'FETCH_WORKITEMS_SUCCESS';
export const FETCH_WORKITEMS_FAILURE = 'FETCH_WORKITEMS_FAILURE';